### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-text-instructions.js#2]
@MoKob can you enable Travis on this repo? There is already a [`.travis.yml`](https://github.com/Project-OSRM/osrm-text-instructions.js/blob/master/.travis.yml) included.

**Comment by MoKob** [comment]
I wish, but I can't. I don't know if @TheMarex has a key here, but otherwise only Dennis can enable travis.

**Comment by MoKob** [comment]
Never mind. Don't need the password when on travis.
